chore: setup build tools
teknologi-umum/httpsnippet pull request #3
Opened 2022-03-13 14:32 UTC by aldy505

2022-03-13 15:24 UTC, elianiva requested changes

2022-03-13 15:24 UTC, elianiva commented on rollup.config.js
> +      name: "flourite",
lupa belom diganti

2022-03-13 15:33 UTC, aldy505 commented on rollup.config.js
> +      name: "flourite",
oh iya

2022-03-18 03:08 UTC, elianiva approved these changes

2022-03-18 03:16 UTC, merged